# Capa propia en castellano: selecciones nacionales y nombres de paises.
# Cada entrada: (nombre en castellano, nombre en ingles tal como aparece en Reep o Wikidata, [alias]).
# Los alias incluyen variantes de escritura, siglas y el nombre en ingles.
SEL = [
 # UEFA
 ("Albania","Albania",[]),
 ("Alemania","Germany",["Deutschland"]),
 ("Andorra","Andorra",[]),
 ("Armenia","Armenia",[]),
 ("Austria","Austria",["Osterreich"]),
 ("Azerbaiyán","Azerbaijan",["Azerbaiyan"]),
 ("Bélgica","Belgium",["Belgica"]),
 ("Bielorrusia","Belarus",["Belarus"]),
 ("Bosnia y Herzegovina","Bosnia and Herzegovina",["Bosnia","Bosnia-Herzegovina"]),
 ("Bulgaria","Bulgaria",[]),
 ("Chipre","Cyprus",[]),
 ("Croacia","Croatia",["Hrvatska"]),
 ("Dinamarca","Denmark",["Kingdom of Denmark"]),
 ("Escocia","Scotland",[]),
 ("Eslovaquia","Slovakia",["Slovak Republic"]),
 ("Eslovenia","Slovenia",[]),
 ("España","Spain",["Espana","La Roja","Seleccion espanola"]),
 ("Estonia","Estonia",[]),
 ("Finlandia","Finland",[]),
 ("Francia","France",[]),
 ("Gales","Wales",[]),
 ("Georgia","Georgia",[]),
 ("Gibraltar","Gibraltar",[]),
 ("Grecia","Greece",[]),
 ("Hungría","Hungary",["Hungria"]),
 ("Inglaterra","England",["Reino Unido","United Kingdom","Gran Bretana"]),
 ("Irlanda","Ireland",["Eire","Republica de Irlanda"]),
 ("Irlanda del Norte","Northern Ireland",[]),
 ("Islandia","Iceland",[]),
 ("Islas Feroe","Faroe Islands",["Feroe","Islas Faroe"]),
 ("Israel","Israel",[]),
 ("Italia","Italy",["Squadra Azzurra"]),
 ("Kazajistán","Kazakhstan",["Kazajistan","Kazajstan"]),
 ("Kosovo","Kosovo",[]),
 ("Letonia","Latvia",[]),
 ("Liechtenstein","Liechtenstein",[]),
 ("Lituania","Lithuania",[]),
 ("Luxemburgo","Luxembourg",[]),
 ("Macedonia del Norte","North Macedonia",["Macedonia"]),
 ("Malta","Malta",[]),
 ("Moldavia","Moldova",["Moldova"]),
 ("Montenegro","Montenegro",[]),
 ("Noruega","Norway",[]),
 ("Países Bajos","Kingdom of the Netherlands",["Paises Bajos","Holanda","Netherlands","Naranja mecanica"]),
 ("Polonia","Poland",[]),
 ("Portugal","Portugal",[]),
 ("República Checa","Czech Republic",["Republica Checa","Chequia","Czechia"]),
 ("Rumanía","Romania",["Rumania"]),
 ("Rusia","Russia",[]),
 ("San Marino","San Marino",[]),
 ("Serbia","Serbia",[]),
 ("Suecia","Sweden",[]),
 ("Suiza","Switzerland",[]),
 ("Turquía","Turkey",["Turquia","Turkiye","Türkiye"]),
 ("Ucrania","Ukraine",[]),
 # CONMEBOL
 ("Argentina","Argentina",[]),
 ("Bolivia","Bolivia",[]),
 ("Brasil","Brazil",["Brazil"]),
 ("Chile","Chile",[]),
 ("Colombia","Colombia",[]),
 ("Ecuador","Ecuador",[]),
 ("Paraguay","Paraguay",[]),
 ("Perú","Peru",["Peru"]),
 ("Uruguay","Uruguay",[]),
 ("Venezuela","Venezuela",[]),
 # CONCACAF
 ("Anguila","Anguilla",[]),
 ("Antigua y Barbuda","Antigua and Barbuda",[]),
 ("Aruba","Aruba",[]),
 ("Bahamas","The Bahamas",[]),
 ("Barbados","Barbados",[]),
 ("Belice","Belize",[]),
 ("Bermudas","Bermuda",["Bermuda"]),
 ("Canadá","Canada",["Canada"]),
 ("Costa Rica","Costa Rica",[]),
 ("Cuba","Cuba",[]),
 ("Curazao","Curaçao",["Curacao"]),
 ("Dominica","Dominica",[]),
 ("El Salvador","El Salvador",[]),
 ("Estados Unidos","United States",["EEUU","EE.UU.","EE UU","USA","US","Estados Unidos de America"]),
 ("Granada","Grenada",[]),
 ("Guatemala","Guatemala",[]),
 ("Guyana","Guyana",[]),
 ("Haití","Haiti",["Haiti"]),
 ("Honduras","Honduras",[]),
 ("Islas Caimán","Cayman Islands",["Islas Caiman"]),
 ("Islas Vírgenes Británicas","British Virgin Islands",["Islas Virgenes Britanicas"]),
 ("Islas Vírgenes de Estados Unidos","United States Virgin Islands",["Islas Virgenes de Estados Unidos"]),
 ("Jamaica","Jamaica",[]),
 ("México","Mexico",["Mexico","Mejico"]),
 ("Montserrat","Montserrat",[]),
 ("Nicaragua","Nicaragua",[]),
 ("Panamá","Panama",["Panama"]),
 ("Puerto Rico","Puerto Rico",[]),
 ("República Dominicana","Dominican Republic",["Republica Dominicana"]),
 ("San Cristóbal y Nieves","Saint Kitts and Nevis",["San Cristobal y Nieves","Saint Kitts","San Cristobal"]),
 ("San Vicente y las Granadinas","Saint Vincent and the Grenadines",["San Vicente"]),
 ("Santa Lucía","Saint Lucia",["Santa Lucia","St. Lucia"]),
 ("Surinam","Suriname",["Suriname"]),
 ("Trinidad y Tobago","Trinidad and Tobago",[]),
 ("Islas Turcas y Caicos","Turks and Caicos Islands",[]),
 # CAF
 ("Angola","Angola",[]),
 ("Argelia","Algeria",[]),
 ("Benín","Benin",["Benin"]),
 ("Botsuana","Botswana",["Botswana"]),
 ("Burkina Faso","Burkina Faso",[]),
 ("Burundi","Burundi",[]),
 ("Cabo Verde","Cape Verde",["Cabo Verde"]),
 ("Camerún","Cameroon",["Camerun"]),
 ("Chad","Chad",[]),
 ("Comoras","Comoros",[]),
 ("Congo","Republic of the Congo",["Republica del Congo"]),
 ("RD Congo","Democratic Republic of the Congo",["Republica Democratica del Congo","DR Congo","RDC","Congo RD"]),
 ("Costa de Marfil","Ivory Coast",["Cote d'Ivoire","Cote dIvoire","Marfil"]),
 ("Egipto","Egypt",[]),
 ("Eritrea","Eritrea",[]),
 ("Esuatini","Eswatini",["Suazilandia","Swazilandia"]),
 ("Etiopía","Ethiopia",["Etiopia"]),
 ("Gabón","Gabon",["Gabon"]),
 ("Gambia","The Gambia",[]),
 ("Ghana","Ghana",[]),
 ("Guinea","Guinea",[]),
 ("Guinea Ecuatorial","Equatorial Guinea",[]),
 ("Guinea-Bisáu","Guinea-Bissau",["Guinea Bisau","Guinea-Bissau"]),
 ("Kenia","Kenya",["Kenya"]),
 ("Lesoto","Lesotho",["Lesotho"]),
 ("Liberia","Liberia",[]),
 ("Libia","Libya",[]),
 ("Madagascar","Madagascar",[]),
 ("Malaui","Malawi",["Malawi"]),
 ("Malí","Mali",["Mali"]),
 ("Marruecos","Morocco",[]),
 ("Mauricio","Mauritius",[]),
 ("Mauritania","Mauritania",[]),
 ("Mozambique","Mozambique",[]),
 ("Namibia","Namibia",[]),
 ("Níger","Niger",["Niger"]),
 ("Nigeria","Nigeria",[]),
 ("Ruanda","Rwanda",["Rwanda"]),
 ("Santo Tomé y Príncipe","São Tomé and Príncipe",["Santo Tome y Principe"]),
 ("Senegal","Senegal",[]),
 ("Seychelles","Seychelles",[]),
 ("Sierra Leona","Sierra Leone",[]),
 ("Somalia","Somalia",[]),
 ("Sudáfrica","South Africa",["Sudafrica"]),
 ("Sudán","Sudan",["Sudan"]),
 ("Sudán del Sur","South Sudan",["Sudan del Sur"]),
 ("Tanzania","Tanzania",[]),
 ("Togo","Togo",[]),
 ("Túnez","Tunisia",["Tunez"]),
 ("Uganda","Uganda",[]),
 ("Yibuti","Djibouti",["Djibouti"]),
 ("Zambia","Zambia",[]),
 ("Zimbabue","Zimbabwe",["Zimbabwe"]),
 # AFC
 ("Afganistán","Afghanistan",["Afganistan"]),
 ("Arabia Saudí","Saudi Arabia",["Arabia Saudita","Arabia Saudi"]),
 ("Australia","Australia",[]),
 ("Baréin","Bahrain",["Barein","Bahrein","Bahréin"]),
 ("Bangladés","Bangladesh",["Banglades"]),
 ("Bután","Bhutan",["Butan"]),
 ("Brunéi","Brunei",["Brunei"]),
 ("Camboya","Cambodia",[]),
 ("China","People's Republic of China",["China","Republica Popular China"]),
 ("Corea del Norte","North Korea",[]),
 ("Corea del Sur","South Korea",["Korea, South","Corea"]),
 ("Emiratos Árabes Unidos","United Arab Emirates",["Emiratos Arabes Unidos","Emiratos","EAU"]),
 ("Filipinas","Philippines",[]),
 ("Guam","Guam",[]),
 ("Hong Kong","Hong Kong",["Hongkong","British Hong Kong"]),
 ("India","India",[]),
 ("Indonesia","Indonesia",[]),
 ("Irak","Iraq",[]),
 ("Irán","Iran",["Iran"]),
 ("Japón","Japan",["Japon"]),
 ("Jordania","Jordan",[]),
 ("Kirguistán","Kyrgyzstan",["Kirguistan","Kirguizistan"]),
 ("Kuwait","Kuwait",[]),
 ("Laos","Laos",[]),
 ("Líbano","Lebanon",["Libano"]),
 ("Macao","Macau",["Macau"]),
 ("Malasia","Malaysia",[]),
 ("Maldivas","Maldives",[]),
 ("Mongolia","Mongolia",[]),
 ("Myanmar","Myanmar",["Birmania"]),
 ("Nepal","Nepal",[]),
 ("Omán","Oman",["Oman"]),
 ("Pakistán","Pakistan",["Pakistan"]),
 ("Palestina","Palestine",[]),
 ("Catar","Qatar",["Qatar"]),
 ("Singapur","Singapore",[]),
 ("Siria","Syria",[]),
 ("Sri Lanka","Sri Lanka",[]),
 ("Tayikistán","Tajikistan",["Tayikistan","Tadzhikistan"]),
 ("Tailandia","Thailand",[]),
 ("Timor Oriental","Timor-Leste",["Timor Este"]),
 ("Turkmenistán","Turkmenistan",["Turkmenistan"]),
 ("Uzbekistán","Uzbekistan",["Uzbekistan"]),
 ("Vietnam","Vietnam",[]),
 ("Yemen","Yemen",[]),
 ("China Taipéi","Chinese Taipei",["China Taipei","Taiwan","Taiwán"]),
 # OFC
 ("Nueva Zelanda","New Zealand",[]),
 ("Fiyi","Fiji",["Fiji"]),
 ("Papúa Nueva Guinea","Papua New Guinea",["Papua Nueva Guinea"]),
 ("Islas Salomón","Solomon Islands",["Islas Salomon"]),
 ("Vanuatu","Vanuatu",[]),
 ("Samoa","Samoa",[]),
 ("Tonga","Tonga",[]),
 ("Islas Cook","Cook Islands",[]),
 ("Nueva Caledonia","New Caledonia",[]),
 ("Tahití","Tahiti",["Tahiti"]),
 # Historicas
 ("Unión Soviética","Soviet Union",["Union Sovietica","URSS","CCCP"]),
 ("Alemania Occidental","West Germany",["RFA","Alemania Federal"]),
 ("Alemania Oriental","German Democratic Republic",["RDA","Alemania del Este"]),
 ("Yugoslavia","Yugoslavia",["Socialist Federal Republic of Yugoslavia","Federal Republic of Yugoslavia"]),
 ("Checoslovaquia","Czechoslovakia",[]),
 ("Serbia y Montenegro","Serbia and Montenegro",[]),
 ("Zaire","Zaire",[]),
]

# Nombres de Wikidata para nacionalidad que no coinciden con las entradas anteriores.
EXTRA_NAT = {
 "United Kingdom":"Reino Unido",
 "United Kingdom of Great Britain and Ireland":"Reino Unido",
 "Kingdom of Italy":"Italia",
 "Kingdom of Yugoslavia":"Yugoslavia",
 "Netherlands":"Países Bajos",
 "Denmark":"Dinamarca",
 "Korea, South":"Corea del Sur",
 "China":"China",
 "Empire of Japan":"Japón",
 "German Reich":"Alemania",
 "German Empire":"Alemania",
 "Nazi Germany":"Alemania",
 "Weimar Republic":"Alemania",
 "Russian Empire":"Rusia",
 "Ottoman Empire":"Turquía",
 "Czech Republic":"República Checa",
 "Cote d'Ivoire":"Costa de Marfil",
 "DR Congo":"RD Congo",
 "Türkiye":"Turquía",
 "The Gambia":"Gambia",
 "The Bahamas":"Bahamas",
 "Cisleithania":"Austria",
 "Austria–Hungary":"Austria-Hungría",
 "Second Polish Republic":"Polonia",
 "Polish People's Republic":"Polonia",
 "Kingdom of Hungary":"Hungría",
 "Socialist Republic of Croatia":"Croacia",
 "Bosnia-Herzegovina":"Bosnia y Herzegovina",
 "Republic of Bosnia and Herzegovina":"Bosnia y Herzegovina",
 "Slovak Republic":"Eslovaquia",
 "Republic of China":"China Taipéi",
 "Chinese Taipei":"China Taipéi",
 "Federal Republic of Yugoslavia":"Yugoslavia",
 "Socialist Federal Republic of Yugoslavia":"Yugoslavia",
 "Kingdom of Serbs, Croats and Slovenes":"Yugoslavia",
 "Democratic Federal Yugoslavia":"Yugoslavia",
 "Georgian Soviet Socialist Republic":"Unión Soviética",
 "Ukrainian Soviet Socialist Republic":"Unión Soviética",
 "Russian Socialist Federative Soviet Republic":"Unión Soviética",
 "Armenian Soviet Socialist Republic":"Unión Soviética",
 "Moldavian Soviet Socialist Republic":"Unión Soviética",
 "People's Republic of Bulgaria":"Bulgaria",
 "Kingdom of Bulgaria":"Bulgaria",
 "Socialist Republic of Romania":"Rumanía",
 "Kingdom of Romania":"Rumanía",
 "Kingdom of Portugal":"Portugal",
 "Irish Free State":"Irlanda",
 "Scotland":"Escocia",
 "Wales":"Gales",
 "England":"Inglaterra",
 "Northern Ireland":"Irlanda del Norte",
 "Kingdom of Scotland":"Escocia",
 "Zimbabwe Rhodesia":"Zimbabue",
 "Belgian Congo":"RD Congo",
 "Zaire":"Zaire",
 "Cote-d'Ivoire":"Costa de Marfil",
 "St. Lucia":"Santa Lucía",
 "Saint Kitts":"San Cristóbal y Nieves",
 "St. Vincent & Grenadinen":"San Vicente y las Granadinas",
}

def nat_map():
    m = {en: es for es, en, _ in SEL}
    m.update(EXTRA_NAT)
    return m
